version: '2'

services:
  postgres:
    image: 'postgres:alpine'
    env_file:
      - '.env'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - '5432:5432'

  website:
    build: .
    command: >
      gunicorn -c "python:config.gunicorn" --reload "funandprofit.app:create_app()"
    env_file:
      - '.env'
    volumes:
      - '.:/funandprofit'
    ports:
      - '8000:8000'

volumes:
  postgres: